name: actividad_1

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: 🏗️ Crear y activar entorno virtual
        run: |
          python -m venv venv
          venv\Scripts\activate && python -m pip install --upgrade pip

      - name: 📦 Instalar dependencias
        run: venv\Scripts\activate && pip install -e .

      - name: 🚀 Ejecutar script
        run: venv\Scripts\activate && python src/pad/actividad_1.py

      - name: 📝 Commit y push de cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización automática desde GitHub Actions"
          commit_user_name: "Sebastián Echeverri [GitHub Actions]"
          commit_user_email: "sebastian.echeverri@est.iudigital.edu.co"
          commit_author: "Sebastian1848 Echeverri <sebastian.echeverri@est.iudigital.edu.co>"
          add_options: "-u" 
